/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * ログイン
     * @description メールアドレスとパスワードを確認し、アクセストークンを発行する
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @example password123
             */
            password: string;
          };
        };
      };
      responses: {
        /** @description ログイン成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        /** @description メールアドレスまたはパスワードが未入力 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description パスワードが誤っている */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description アカウントが存在しない */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description バリデーションエラー */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * ログアウト
     * @description 現在のトークンを削除し、ログアウトする
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ログアウト成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example ログアウトしました。 */
              message?: string;
            };
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * ユーザー登録
     * @description 新規ユーザーを登録する。登録完了後は自動的にログイン状態となり、個人ワークスペースを自動生成する
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @example admin@example.com
             */
            email: string;
            /**
             * Format: password
             * @example Password
             */
            password: string;
            /** @example 管理者太郎 */
            name?: string;
          };
        };
      };
      responses: {
        /** @description ユーザー登録成功 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        /** @description メールアドレスまたはパスワードが未入力 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description メールアドレスが既に使用されている */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description バリデーションエラー */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ユーザー情報取得
     * @description ログインユーザーの情報を取得する
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ユーザー情報取得成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UserResponse"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * プロフィール更新
     * @description ログインユーザーの表示名を更新する
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example 新しいユーザー名 */
            name: string;
          };
        };
      };
      responses: {
        /** @description プロフィール更新成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example 新しいユーザー名 */
              name?: string;
            };
          };
        };
        /** @description nameが未入力 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    trace?: never;
  };
  "/api/users/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * パスワード変更
     * @description ログインユーザーのパスワードを変更する
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: password
             * @example currentPassword123
             */
            currentPassword: string;
            /**
             * Format: password
             * @example newPassword123
             */
            newPassword: string;
          };
        };
      };
      responses: {
        /** @description パスワード変更成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example パスワードの変更が完了しました。 */
              message?: string;
            };
          };
        };
        /** @description currentPasswordまたはnewPasswordが未入力 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description バリデーションエラー */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    trace?: never;
  };
  "/api/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ワークスペース一覧取得
     * @description ログインユーザーが参加しているワークスペース一覧を取得する
     */
    get: {
      parameters: {
        query?: {
          /** @description 種別での絞り込み */
          type?: "PERSONAL" | "GROUP";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 取得成功（0件の場合は空配列） */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              workspaces?: components["schemas"]["WorkspaceSummary"][];
            };
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /**
     * ワークスペース作成
     * @description グループワークスペースを作成する。作成者は管理者となる
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * @description 未入力の場合は "Group" をデフォルト名とする
             * @example 開発チーム
             */
            name?: string;
          };
        };
      };
      responses: {
        /** @description ワークスペース作成成功 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["WorkspaceDetail"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description バリデーションエラー */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{workspaceId}/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * ワークスペース招待リンク発行
     * @description グループワークスペースへの招待リンクを発行する。管理者権限が必要
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ワークスペースID */
          workspaceId: components["parameters"]["workspaceId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description 招待リンク発行成功 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example invite_token_sample */
              inviteToken?: string;
              /**
               * Format: date-time
               * @example 2026-05-20T10:00:00Z
               */
              expiresAt?: string;
            };
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 管理者権限がない */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description ワークスペースが存在しない */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description GROUPタイプ以外のワークスペースへの招待 */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/invitations/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * ワークスペース参加
     * @description 招待トークンを使用してグループワークスペースに参加する
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example invite_token_sample */
            inviteToken: string;
          };
        };
      };
      responses: {
        /** @description ワークスペース参加成功 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["WorkspaceDetail"];
          };
        };
        /** @description inviteTokenが未入力 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 招待トークンが無効または期限切れ */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 既に参加済み */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{workspaceId}/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * カテゴリ一覧取得
     * @description 指定ワークスペースのカテゴリ一覧を取得する（論理削除済みは除く）
     */
    get: {
      parameters: {
        query?: {
          /** @description 種別での絞り込み */
          type?: "INCOME" | "EXPENSE";
        };
        header?: never;
        path: {
          /** @description ワークスペースID */
          workspaceId: components["parameters"]["workspaceId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 取得成功（0件の場合は空配列） */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              categories?: components["schemas"]["CategoryResponse"][];
            };
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description ワークスペースが存在しない */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /**
     * カテゴリ作成
     * @description 指定ワークスペースにカテゴリを新規作成する
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ワークスペースID */
          workspaceId: components["parameters"]["workspaceId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example 食費 */
            name: string;
            /**
             * @example EXPENSE
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE";
            /** @example #FF5733 */
            color?: string;
          };
        };
      };
      responses: {
        /** @description カテゴリ作成成功 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CategoryResponse"];
          };
        };
        /** @description リクエストパラメータが不正 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 同名のカテゴリが既に存在する */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{workspaceId}/categories/{categoryId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * カテゴリ編集
     * @description 既存のカテゴリを編集する
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ワークスペースID */
          workspaceId: components["parameters"]["workspaceId"];
          /** @description カテゴリID */
          categoryId: components["parameters"]["categoryId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example 外食費 */
            name: string;
            /**
             * @example EXPENSE
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE";
            /** @example #FFA500 */
            color?: string;
          };
        };
      };
      responses: {
        /** @description カテゴリ更新成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CategoryResponse"];
          };
        };
        /** @description リクエストパラメータが不正 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description カテゴリが存在しない */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 同名のカテゴリが既に存在する */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    post?: never;
    /**
     * カテゴリ削除
     * @description カテゴリを論理削除する
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ワークスペースID */
          workspaceId: components["parameters"]["workspaceId"];
          /** @description カテゴリID */
          categoryId: components["parameters"]["categoryId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 削除成功（レスポンスボディなし） */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description カテゴリが存在しない、または既に削除済み */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{workspaceId}/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 収支履歴取得
     * @description 指定した月の収支データを全件取得する（日付降順）
     */
    get: {
      parameters: {
        query: {
          /** @description 対象年月（YYYY-MM形式） */
          yearMonth: string;
        };
        header?: never;
        path: {
          /** @description ワークスペースID */
          workspaceId: components["parameters"]["workspaceId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 取得成功（0件の場合はtransactionsが空配列） */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example 2026-05 */
              yearMonth?: string;
              transactions?: components["schemas"]["TransactionResponse"][];
            };
          };
        };
        /** @description yearMonthが未指定または形式不正 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description ワークスペースが存在しない */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /**
     * 収支登録
     * @description 収支データを登録する
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ワークスペースID */
          workspaceId: components["parameters"]["workspaceId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example 1 */
            categoryId: number;
            /**
             * @example EXPENSE
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE";
            /** @example 1500 */
            amount: number;
            /**
             * Format: date
             * @example 2026-05-14
             */
            date: string;
            /** @example ランチ代 */
            memo?: string;
          };
        };
      };
      responses: {
        /** @description 収支登録成功 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TransactionResponse"];
          };
        };
        /** @description リクエストパラメータが不正 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description カテゴリが存在しない */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{workspaceId}/transactions/{transactionId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 収支編集
     * @description 既存の収支データを編集する
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ワークスペースID */
          workspaceId: components["parameters"]["workspaceId"];
          /** @description 収支ID */
          transactionId: components["parameters"]["transactionId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example 2 */
            categoryId: number;
            /**
             * @example EXPENSE
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE";
            /** @example 2000 */
            amount: number;
            /**
             * Format: date
             * @example 2026-05-14
             */
            date: string;
            /** @example 夕食代に変更 */
            memo?: string;
          };
        };
      };
      responses: {
        /** @description 収支更新成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TransactionResponse"];
          };
        };
        /** @description リクエストパラメータが不正 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 収支データまたはカテゴリが存在しない */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    post?: never;
    /**
     * 収支削除
     * @description 収支データを論理削除する
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ワークスペースID */
          workspaceId: components["parameters"]["workspaceId"];
          /** @description 収支ID */
          transactionId: components["parameters"]["transactionId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 削除成功（レスポンスボディなし） */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 収支データが存在しない、または既に削除済み */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      /** @example ALREADY_EXISTS */
      errorCode?: string;
      /** @example このメールアドレスは既に登録されています。 */
      message?: string;
    };
    UserResponse: {
      /** @example 1 */
      userId?: number;
      /** @example user@example.com */
      email?: string;
      /** @example 管理者太郎 */
      name?: string;
    };
    AuthResponse: {
      /** @example 1 */
      userId?: number;
      /** @example user@example.com */
      email?: string;
      /** @example 管理者太郎 */
      name?: string;
      /**
       * Format: date-time
       * @example 2026-05-14T10:00:00Z
       */
      createdAt?: string;
      /** @example eyJhbGciOiJIUzI1NiJ9... */
      accessToken?: string;
      workspaces?: components["schemas"]["WorkspaceSummary"][];
    };
    WorkspaceSummary: {
      /** @example 1 */
      workspaceId?: number;
      /** @example 個人ワークスペース */
      workspaceName?: string;
      /**
       * @example PERSONAL
       * @enum {string}
       */
      type?: "PERSONAL" | "GROUP";
      /**
       * @example ADMIN
       * @enum {string}
       */
      role?: "ADMIN" | "MEMBER";
    };
    WorkspaceMember: {
      /** @example 1 */
      userId?: number;
      /** @example user1 */
      name?: string;
      /**
       * @example ADMIN
       * @enum {string}
       */
      role?: "ADMIN" | "MEMBER";
    };
    WorkspaceDetail: {
      /** @example 10 */
      workspaceId?: number;
      /** @example 開発チーム */
      workspaceName?: string;
      /**
       * @example GROUP
       * @enum {string}
       */
      type?: "GROUP";
      members?: components["schemas"]["WorkspaceMember"][];
    };
    CategoryResponse: {
      /** @example 1 */
      id?: number;
      /** @example 10 */
      workspaceId?: number;
      /** @example 食費 */
      name?: string;
      /**
       * @example EXPENSE
       * @enum {string}
       */
      type?: "INCOME" | "EXPENSE";
      /** @example #FF5733 */
      color?: string;
      /**
       * Format: date-time
       * @example 2026-05-14T10:00:00Z
       */
      createdAt?: string;
    };
    TransactionResponse: {
      /** @example 100 */
      id?: number;
      /** @example 10 */
      workspaceId?: number;
      /** @example 1 */
      categoryId?: number;
      /** @example 食費 */
      categoryName?: string;
      /** @example #FF5733 */
      categoryColor?: string;
      /**
       * @example EXPENSE
       * @enum {string}
       */
      type?: "INCOME" | "EXPENSE";
      /** @example 1500 */
      amount?: number;
      /**
       * Format: date
       * @example 2026-05-14
       */
      date?: string;
      /** @example ランチ代 */
      memo?: string;
      /** @example 管理者太郎 */
      registeredBy?: string;
      /**
       * Format: date-time
       * @example 2026-05-14T12:30:00Z
       */
      createdAt?: string;
    };
  };
  responses: never;
  parameters: {
    /** @description ワークスペースID */
    workspaceId: number;
    /** @description カテゴリID */
    categoryId: number;
    /** @description 収支ID */
    transactionId: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
