create table users(
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    system_role VARCHAR NOT NULL DEFAULT 'USER' CHECK(system_role IN('USER','ADMIN')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE 
);

CREATE TABLE workspaces(
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(20) NOT NULL CHECK(type in ('PERSONAL','GROUP')),
  owner_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE workspace_members(
id BIGSERIAL PRIMARY KEY,
workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
user_id BIGINT NOT NULL REFERENCES users(id),
role VARCHAR(20) NOT NULL CHECK(role IN('ADMIN','MEMBER')),
status VARCHAR(20) NOT NULL CHECK(status IN('ACTIVE','LEFT')),
joined_at TIMESTAMP NOT NULL,
left_at TIMESTAMP NULL,
UNIQUE(workspace_id,user_id)
);

CREATE TABLE categories(
id BIGSERIAL PRIMARY KEY,
workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
name VARCHAR(50) NOT NULL,
color VARCHAR(7) NOT NULL,
type VARCHAR(20) NOT NULL CHECK(type IN('INCOME','EXPENSE')),
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE expenses(
id BIGSERIAL PRIMARY KEY,
workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
user_id BIGINT NOT NULL REFERENCES users(id),
category_id BIGINT NOT NULL REFERENCES categories(id),
amount DECIMAL(12,2) NOT NULL CHECK(amount >= 0),
transaction_type VARCHAR(10) NOT NULL CHECK (transaction_type IN('INCOME','EXPENSE')),
transaction_date DATE NOT NULL,
memo VARCHAR(500),
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE
);