create table users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100),
    system_role VARCHAR NOT NULL DEFAULT 'USER' CHECK(type IN('USER','ADMIN')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE 
);

CREATE TABLE workspaces(
  id BIGINT PRIMARY SERIAL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(20) NOT NULL CHECK(type in ('PERSONAL','GROUP')),
  FOREIGN KEY (owner_user_id) REFERENCES users(id) BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE workspace_members(
id BIGINT PK SERIAL,
FOREIGN KEY (workspace_id) REFERENCES workspaces(id) BIGINT NOT NULL UNIQUE,
FOREIGN KEY (user_id) REFERENCES users(id) BIGINT NOT NULL UNIQUE,
role VARCHAR(20) NOT NULL CHECK(type IN('ADMIN','MEMBER')),
status VARCHAR(20) NOT NULL CHECK(type IN('ADMIN','MEMBER')),
joined_at TIMESTAMP NOT NULL,
left_at TIMESTAMP NOT NULL
);

CREATE TABLE categories(
id BIGINT PK SERIAL,
FOREIGN KEY (workspace_id) REFERENCES workspaces(id) NOT NULL BIGINT,
name VARCHAR(50) NOT NULL,
color VARCHAR(7) NOT NULL,
type VARCHAR(20) NOT NULL CHECK(type IN('INCOME','EXPENSE')),
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE expenses(
id PK BIGINT SERIAL,
FOREIGN KEY (workspace_id) REFERENCES workspaces(id) BIGINT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id) BIGINT NOT NULL,
FOREIGN KEY (category_id) REFERENCES categories(id) BIGINT NOT NULL,
CONSTRAINT amount DECIMAL(12,2) NOT NULL CHECK(amount >= 0),
transaction_type VARCHAR(10) NOT NULL CHECK (type IN('INCOME','EXPENSE')),
transaction_date DATE NOT NULL,
memo VARCHAR(500),
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE
);