CREATE TABLE workspaces(
  id BIGINT PRIMARY SERIAL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(20) NOT NULL CHECK(type in ('PERSONAL','GROUP')),
  FOREIGN KEY (owner_user_id) REFERENCES users(id) BIGINT NOT NULL, 
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE
);