CREATE TABLE workspace_members(
id BIGINT PK SERIAL,
FOREIGN KEY (workspace_id) REFERENCES workspaces(id) BIGINT NOT NULL UNIQUE,
FOREIGN KEY (user_id) REFERENCES users(id) BIGINT NOT NULL UNIQUE,
role VARCHAR(20) NOT NULL CHECK(type IN('ADMIN','MEMBER')),
status VARCHAR(20) NOT NULL CHECK(type IN('ADMIN','MEMBER')),
joined_at TIMESTAMP NOT NULL,
left_at TIMESTAMP NOT NULL
);