CREATE TABLE categories(
id BIGINT PK SERIAL,
FOREIGN KEY (workspace_id) REFERENCES workspaces(id) NOT NULL BIGINT,
name VARCHAR(50) NOT NULL,
color VARCHAR(7) NOT NULL,
type VARCHAR(20) NOT NULL CHECK(type IN('INCOME','EXPENSE')),
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE
);