CREATE TABLE expenses(
id PK BIGINT SERIAL,
FOREIGN KEY (workspace_id) REFERENCES workspaces(id) BIGINT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id) BIGINT NOT NULL,
FOREIGN KEY (category_id) REFERENCES categories(id) BIGINT NOT NULL,
amount DECIMAL(12,2) NOT NULL CHECK(amount >= 0),
transaction_type VARCHAR(10) NOT NULL CHECK (type IN('INCOME','EXPENSE')),
transaction_date DATE NOT NULL,
memo VARCHAR(500),
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE
);