spring.application.name=FamilyFinances
# ????????????
server.port=8089

# ===============================
# ? PostgreSQL ??????????
# ===============================
# URL: localhost?5432??????? family_finances ???DB???
spring.datasource.url=jdbc:postgresql://localhost:5450/family_finances
# ??????Docker????????
spring.datasource.username=postgres
# ??????Docker????????
spring.datasource.password=postgres
# ?????????????
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# ?? JPA / Flyway ???
# ===============================
# JPA????????????????????????Flyway???????
spring.jpa.hibernate.ddl-auto=validate
# ?????SQL???????????????????????????
spring.jpa.show-sql=true

# DB?????????Flyway?????
spring.flyway.enabled=true