spring:
  application:
    name: FamilyFinances

  # ===============================
  #  PostgreSQL 
  # ===============================
  datasource:
    # URL: localhost5450 family_finances DB
    url: jdbc:postgresql://localhost:5450/family_finances
    # Docker
    username: postgres
    # Docker
    password: postgres
    # 
    driver-class-name: org.postgresql.Driver

  # ===============================
  #  JPA / Flyway 
  # ===============================
  jpa:
    hibernate:
      # JPAFlyway
      ddl-auto: validate
    # SQL
    show-sql: true

  # DBFlyway
  flyway:
    enabled: true

# 
server:
  port: 8089