spring:
  application:
    name: FamilyFinances

  # ===============================
  # ? PostgreSQL ??????????
  # ===============================
  datasource:
    # URL: localhost?5450??????? family_finances ???DB???
    url: jdbc:postgresql://localhost:5450/family_finances
    # ??????Docker????????
    username: postgres
    # ??????Docker????????
    password: postgres
    # ?????????????
    driver-class-name: org.postgresql.Driver

  # ===============================
  # ?? JPA / Flyway ???
  # ===============================
  jpa:
    hibernate:
      # JPA????????????????????????Flyway???????
      ddl-auto: validate
    # ?????SQL???????????????????????????
    show-sql: true

  # DB?????????Flyway?????
  flyway:
    enabled: true

# ????????????
server:
  port: 8089